# Sequence scorer finetuning with pairwise comparisons annotations

This notebook is based on an approach for fine-tuning a text item-level scoring model based on pairwise comparison annotations presented in

> Hauke Licht, Rupak Sarkar, Patrick Y. Wu, Pranav Goel, Niklas Stoehr, Elliott Ash, and Alexander Miserlis Hoyle. 2025. **Measuring scalar constructs in social science with LLMs.** In _Proceedings of the 2025 Conference on Empirical Methods in Natural Language Processing_, pages 32144–32171, Suzhou, China. Association for Computational Linguistics. URL:https://aclanthology.org/2025.emnlp-main.1635/

<a target="_blank" href="https://colab.research.google.com/github/haukelicht/advanced_text_analysis/blob/main/notebooks/encoder_finetuning/finetune_sequence_scorer_pairwise.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


## Background

### Pairwise comparison

**goal:** use pairwise data to estimate items' scores 

![Illustration of fine-tuning scoring model from pairwise comparisons data](../.assets/task_types-pairwise_comparison.svg)

methodological motivation:

- many concepts are latent and conceptually continuous
- text items' locations on this scale are hard to observe directly
- human annotators are bad at directly scoring items on the scales (inconsistent over-time, different scales, different anchors)
- comparison captures relative differences between pairs of items
- underlying scale can be estimated from pairwise comparisons data (e.g., Bradley--Terry model)

Characteristics:

- _text pair-level_ classification: assign pairs of documents (e.g., sentences) to categories
- single-label classification: assign pair to one and of two categories ("first" or "second" text)

### methods papers and research applications

- Hauke Licht, Rupak Sarkar, Patrick Y. Wu, Pranav Goel, Niklas Stoehr, Elliott Ash, and Alexander Miserlis Hoyle. 2025. Measuring scalar constructs in social science with LLMs. In _Proceedings of the 2025 Conference on Empirical Methods in Natural Language Processing_, pages 32144–32171, Suzhou, China. Association for Computational Linguistics.
- Wu P, Nagler J, Tucker JA, Messing S. Concept-Guided Chain-of-Thought Prompting for Pairwise Comparison Scaling of Texts with Large Language Models. 2023. working paper
- Benoit K, Munger K, Spirling A. Measuring and Explaining Political So- phistication through Textual Complexity. 2019. *American Journal of Political Science*; 63(2): 491–508.
- Carlson D, Montgomery JM. A Pairwise Comparison Framework for Fast, Flexible, and Reliable Human Coding of Political Texts. 2017. *American Political Science Review*; 111(4): 835–843.

### fine-tuning implementation

given 

- $n$ training examples ($x_i$, $x_j$, $y_{ij}$) where 
	- $x_i$ is item i's text, 
	- $x_j$ is item j's text, and
	- $y_{ii}$ is "1" if first item wins and "2" if second item wins
- a (pre-trained) model that 
	- intakes text representations ($x_k$)
	- outputs score $\hat{s}_k$ that estimates item $k$'s strength
- loss function: $\log(\sigma(s_w - s_l))$ ("reward loss") the smaller, the bigger the difference between the "winner" and "loser" items' predicted scores

## Setup

#### Colab

In [45]:
# check if on Colab
COLAB = True
try:
  from google import colab
except:
  COLAB = False

if COLAB:
    # shallow clone of current state of main branch 
    !git clone --branch main --single-branch --depth 1 --filter=blob:none https://github.com/haukelicht/advanced_text_analysis.git
    
    # make repo root findable for python
    import sys
    sys.path.append("/content/advanced_text_analysis/")

    %pip install -q -U accelerate==0.21.0 trl~=1.12.0 bitsandbytes

#### Install required packages

In [46]:
from pathlib import Path
import numpy as np
import pandas as pd

from src.utils.io import read_tabular
from src.finetuning import unpair_data

from datasets import Dataset, DatasetDict
from transformers import (
    AutoTokenizer, 
    AutoModelForSequenceClassification,
    pipeline
)
from transformers.pipelines.pt_utils import KeyDataset

from trl import (
    ModelConfig,
    RewardTrainer,
    RewardConfig, # similar to transformers' TrainingArguments
    # get_kbit_device_map, # uncomment if you are on machine with a CUDA GPU supporting `bitsandbytes`
    get_peft_config,
    get_quantization_config,
)

from tqdm.auto import tqdm

In [47]:
MODEL_NAME = 'answerdotai/ModernBERT-base'

In [48]:
base_path = Path("/content/advanced_text_analysis/" if COLAB else "../../")

data_path = base_path / "data" / "labeled" / "hargrave_no_2022"
data_file = "hargrave_no_2022-complexity.tsv"

## Load and prepare the data

In [49]:
# same dataset used (in unpaired form) in finetune_sequence_scorer.ipynb
fp = data_path / data_file
if not fp.exists():
    url = f"https://cta-text-datasets.s3.eu-central-1.amazonaws.com/labeled/{data_path.parent.name}/{data_file}"
    df = pd.read_csv(url, sep="\t")
    fp.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(fp, sep="\t", index=False)

In [50]:
data = read_tabular(str(fp)).to_dict(orient='records')

In [51]:
# keep only relevant fields, renaming ids to match the id1/id2 naming `unpair_data` expects
# and recoding metadata__comparison to label = 1 if text1 wins, 2 if text2 wins, 0 if tie
comparison2label = {1: 1, -1: 2, 0: 0}
data = [
    {
        'pair_id': d['pair_id'],
        'id1': d['text1_id'],
        'id2': d['text2_id'],
        'text1': d['text1'],
        'text2': d['text2'],
        'label': comparison2label[d['metadata__comparison']],
    }
    for d in data
]

In [52]:
# note: a single example has the texts that were compared, their IDs, and the label
# label = 2 if text2>text1, 1 if text1>text2, 0 otherwise ("tie")
data[0]

{'pair_id': '03d99bf9d3de00bd8fc2534a8f846882',
 'id1': 'a0cb6dfc4d341be336265beddf2dd921',
 'id2': '63054fe83c288894043d98fdc6e3097e',
 'text1': 'The people of France and the Netherlands voted against the EU constitution, which as the former Irish Taoiseach, Bertie Ahern, acknowledged was 90 per cent. the same as the treaty of Lisbon, so in fact 21 million people have voted in referendums against the European constitution and the treaty of Lisbon, which is the constitution by another name.',
 'text2': 'I echo warmly the call of my hon  Friend  the Member for Croydon Central    for a debate on the opportunities afforded by academies, focusing particularly on the benefit of vertical integration between primary and secondary academies.',
 'label': 1}

In [53]:
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, use_fast=True)
if not tokenizer.pad_token:
    tokenizer.pad_token = tokenizer.eos_token
    tokenizer.pad_token_id = tokenizer.eos_token_id

In [54]:
max_tokens = max(tokenizer([d['text'] for d in unpair_data(data)], return_length=True, truncation=False)['length'])
max_tokens

118

In [55]:
from src.finetuning import split_data
data_splits = split_data(data, test_size=0.2, dev_size=0.2, seed=42, return_dict=True)

In [56]:
datasets = DatasetDict({
    s: Dataset.from_list(data)
    for s, data in data_splits.items()
})

In [57]:
assert max_tokens <= tokenizer.model_max_length, f"Error: The max_seq_length passed ({max_tokens}) is larger than the maximum length for the model ({tokenizer.model_max_length})."
max_seq_length = min(max_tokens, tokenizer.model_max_length)

In [59]:
def paired_preprocess_function(examples):
    new_examples = {
        "chosen_ids": [],
        "chosen_attention_mask": [],
        "rejected_ids": [],
        "rejected_attention_mask": [],
        "is_tie": [],
    }
    for text1, text2, label in zip(examples["text1"], examples["text2"], examples["label"]):
        _tokenize = lambda x: tokenizer(x, max_length=max_seq_length, truncation=True)
        is_tie = label == 0
        if label == 1 or label == 0:
            tokenized_chosen, tokenized_rejected = _tokenize(text1), _tokenize(text2)
        elif label == 2:
            tokenized_chosen, tokenized_rejected = _tokenize(text2), _tokenize(text1)
        else:
            raise ValueError("Label must be `1` or `2` to indicate index of chosen item, `0` for ties.")

        new_examples["chosen_ids"].append(tokenized_chosen["input_ids"])
        new_examples["chosen_attention_mask"].append(tokenized_chosen["attention_mask"])
        new_examples["rejected_ids"].append(tokenized_rejected["input_ids"])
        new_examples["rejected_attention_mask"].append(tokenized_rejected["attention_mask"])
        new_examples["is_tie"].append(is_tie)
    return new_examples

In [60]:
datasets = datasets.map(paired_preprocess_function, batched=True, num_proc=1)

Map (num_proc=1):   0%|          | 0/59 [00:00<?, ? examples/s]

Map (num_proc=1):   0%|          | 0/19 [00:00<?, ? examples/s]

Map (num_proc=1):   0%|          | 0/19 [00:00<?, ? examples/s]

In [61]:
datasets.num_rows

{'train': 59, 'dev': 19, 'test': 19}

## setup the reward modeling

In [ ]:
model_path = base_path / "models" / "hargrave_no_2022-complexity-scorer"

reward_config = RewardConfig(
    output_dir=model_path,
    max_length=max_seq_length,
    
    do_train=True,
    num_train_epochs=3,
    per_device_train_batch_size=16,
    gradient_accumulation_steps=1,
    learning_rate=5e-05,
    optim='adamw_torch',
    
    do_eval=True,
    eval_strategy='epoch',
    per_device_eval_batch_size=32,
    
    load_best_model_at_end=True,
    metric_for_best_model='accuracy',
    save_strategy='epoch',
    save_total_limit=2,

    seed=42,
    data_seed=42,
)

In [65]:
model_config = ModelConfig(MODEL_NAME, lora_task_type='SEQ_CLS')

In [66]:
quantization_config = get_quantization_config(model_config)

In [67]:
model_kwargs = dict(
    revision=model_config.model_revision,
    trust_remote_code=True, # model_config.trust_remote_code,
    device_map="auto", #get_kbit_device_map() if quantization_config is not None else "auto",
    quantization_config=quantization_config,
)

In [22]:
# NOTE: passing a custom `compute_metrics` to RewardTrainer does not work reliably in trl 1.12:
#  the collator concatenates each batch as [all chosen] + [all rejected] (2x the dataset's row
#  count), but `Trainer.evaluation_loop` gathers predictions via `accelerate.gather_for_metrics`,
#  which truncates the output back down to the *dataset's* row count, silently keeping only the
#  first half (the chosen-item rewards) and dropping the rejected-item rewards. So a compute_metrics
#  function has no way to compare chosen vs. rejected scores from `predictions`/`predict()` output.
# Instead, rely on the accuracy/margin/reward stats RewardTrainer already computes internally in
#  `compute_loss` (before that truncation happens) and logs automatically, e.g. `eval_accuracy`.

In [68]:
model = AutoModelForSequenceClassification.from_pretrained(model_config.model_name_or_path, num_labels=1, **model_kwargs)
model.config.pad_token_id = tokenizer.pad_token_id

trainer = RewardTrainer(
    model=model,
    processing_class=tokenizer,
    args=reward_config,
    train_dataset=datasets['train'],
    eval_dataset=datasets['dev'],
    peft_config=get_peft_config(model_config),
)

Loading weights:   0%|          | 0/136 [00:00<?, ?it/s]

[transformers] ModernBertForSequenceClassification LOAD REPORT from: answerdotai/ModernBERT-base
Key               | Status     |
------------------+------------+-
decoder.bias      | UNEXPECTED |
classifier.weight | MISSING    |
classifier.bias   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Filtering train >118 tokens:   0%|          | 0/59 [00:00<?, ? examples/s]

Filtering eval >118 tokens:   0%|          | 0/19 [00:00<?, ? examples/s]

## Finetune

In [69]:
train_result = trainer.train(ignore_keys_for_eval=["hidden_states"])

[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': None, 'bos_token_id': None}.
/Users/hlicht/miniforge3/envs/advanced_text_analysis/lib/python3.11/site-packages/torch/utils/data/dataloader.py:752: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/Users/hlicht/miniforge3/envs/advanced_text_analysis/lib/python3.11/site-packages/torch/utils/data/dataloader.py:752: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/Users/hlicht/miniforge3/envs/advanced_text_analysis/lib/python3.11/site-packages/torch/utils/data/dataloader.py:752: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/Users/hlicht/miniforge3/envs/advanced_text_analysis/lib/python3.11/site-packages/torch/utils/data/dataloader.py:752: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/Users/hlicht/miniforge3/envs/advanced_text_analysis/lib/python3.11/site-packages/torch/utils/data/dataloader.py:752: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

In [70]:
trainer.evaluate(datasets['test'], metric_key_prefix='test')

Filtering eval >118 tokens:   0%|          | 0/19 [00:00<?, ? examples/s]

/Users/hlicht/miniforge3/envs/advanced_text_analysis/lib/python3.11/site-packages/torch/utils/data/dataloader.py:752: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

{'test_loss': 0.3549951910972595,
 'eval_num_tokens': 33855.0,
 'eval_min_reward': -1.7109375,
 'eval_mean_reward': 4.1064300537109375,
 'eval_max_reward': 11.5625,
 'eval_accuracy': 0.7894737124443054,
 'eval_margin': 3.9947268962860107}

### item-level scoring

Remember that the underyling model is a sequence classification model with a single output neuron (i.e., a scoring/regression model).

In [72]:
print("model type:", type(trainer.model).__name__)
print("number of output neurons:", trainer.model.config.num_labels)

model type: ModernBertForSequenceClassification
number of output neurons: 1

So we can pass it indiviudal texts to score them with the fine-tuned model.

For this, we first need to unnest/unpack/unpair the text pair-level data into individual text items:

In [73]:
# unpack the pair-level data to item-level data
items_dataset = unpair_data(datasets['test'])

# look at the first item
items_dataset[0]

# make it a Dataset instance
items_dataset = Dataset.from_list(items_dataset)

In [74]:
# NOTE: for convenicene we use huggingface's pipeline class for inference with out scoring/regression model 
scorer = pipeline(task="text-classification", model=trainer.model, tokenizer=tokenizer, batch_size=32)

In [75]:
# example
scorer(items_dataset['text'][0])

[{'label': 'LABEL_0', 'score': 0.21733753383159637}]

In [76]:
# for batch inference (see https://huggingface.co/docs/transformers/pipeline_tutorial#batch-inference)
kd = KeyDataset(items_dataset, "text")

pred_scores = np.array([p['score'] for p in tqdm(scorer(kd, batch_size=32), total=len(items_dataset))])

  0%|          | 0/38 [00:00<?, ?it/s]

In [77]:
# get indexes of 5 highest scoring items
idxs = np.argsort(pred_scores)[-5:]
print(*items_dataset.select(idxs)['text'], sep='\n')

Will the right hon  Gentleman arrange time for the House to debate the suitability, or otherwise, of the well known Australian property developer and pop impresario Lord Levy - who masquerades as the Government's envoy to the middle east and who caused the right hon  Gentleman such trouble by meddling in the middle east during the period when he was a distinguished Foreign Secretary - to continue in that role without being in any way accountable to Parliament at one of the most difficult and serious passages of international affairs for many years?
Last year, the shadow Secretary of State for Work and Pensions, my hon  Friend  the Member for Leeds West   , reviewed the issue and, based on an investigation of the available evidence and widespread consultation with the industry, we have proposed that workers should automatically be deemed to be treated as employees for tax purposes if they meet criteria that most people would regard as obvious signs that they were employees rather than self-employed subcontractors.
It is a notable feature of the EU negotiations in which the Government are involved at this moment that, although the rights of EU citizens in this country now seem to be protected, British citizens living in other EU countries will have inferior rights because those rights will exist only in the countries where they are currently resident; the rights will not be passportable because those people will lose the right to freedom of movement between other EU countries.
Under the original rules, local authorities in areas of outstanding natural beauty were allowed to include a covenant limiting the freedom of the tenant to sell on property that they purchased to people living or working in the area, so creating a second tier to the housing market in those areas that allows more affordable house sales and helps to ensure local people have the opportunity to get on to the property ladder at an affordable price in the area in which they  have strong local connections.
The key elements of the proposal are the introduction of a phased ban on the discarding of commercial fish; decentralisation of decision-making, away from micro-management in Brussels; a longer-term approach focused on the introduction of multi-annual plans that deliver maximum sustainable yield by 2015; integration of fisheries management with other marine policies; market measures allocating transferable fishing concessions; improvements in the sustainability and transparency of fisheries agreements with developing countries under the CFP's external dimension; and commitments to improve scientific knowledge and encourage the development of sustainable aquaculture.

In [78]:
# get indexes of 5 lowest scoring items
idxs = np.argsort(pred_scores)[:5]
print(*items_dataset.select(idxs)['text'], sep='\n')

There is much more to be done about that as well, but I am very pleased with all the amendments.
It is because she does not have a majority that she needs to do so.
My share of the vote went up by 50%, to 60%.
Another terrible tragedy was the death of Christopher Smith, who was only seven years old.
So there are concerns about the way in which the process works at the moment.

In [79]:
texts = [
    "We will protect public services.",
    "The government will introduce targeted measures to reduce household energy costs while maintaining fiscal discipline.",
    "Although the proposed reform may improve administrative efficiency, its long-term success will depend on whether local authorities receive sufficient resources to implement the new regulatory framework consistently.",
    "In confronting the intertwined challenges of economic stagnation, regional inequality, and declining institutional trust, Parliament must pursue a coherent strategy that reconciles immediate social protections with durable structural reform.",
    "Notwithstanding the legitimate concerns raised by opposition members, the government contends that a carefully sequenced programme of investment, regulatory modernization, and intergovernmental coordination offers the most credible means of strengthening democratic resilience without compromising fiscal sustainability.",
    "Pursuant to Standing Order No. 83J, the programme motion and associated Ways and Means resolution shall be taken forthwith, after which the Bill will be recommitted to a Committee of the whole House for consideration of the remaining clauses and schedules."
]

preds = scorer(texts)
preds_df = pd.DataFrame(preds)
preds_df['text'] = texts
preds_df[['text', 'score']]

                                                text     score
0                   We will protect public services.  0.230920
1  The government will introduce targeted measure...  0.734120
2  Although the proposed reform may improve admin...  0.631594
3  In confronting the intertwined challenges of e...  0.875787
4  Notwithstanding the legitimate concerns raised...  0.997110
5  Pursuant to Standing Order No. 83J, the progra...  0.975577